// <auto-generated />
using System;
using KuranGuide.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuranGuide.Infrastructure.Migrations
{
    [DbContext(typeof(KuranGuideDbContext))]
    [Migration("20260106063753_MakeHadisAciklamaNullable")]
    partial class MakeHadisAciklamaNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KuranGuide.Domain.Entities.Ayet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArapcaMetin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AyetNo")
                        .HasColumnType("int");

                    b.Property<string>("Meal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SureId")
                        .HasColumnType("int");

                    b.Property<int?>("TemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SureId");

                    b.HasIndex("TemaId");

                    b.ToTable("Ayetler", (string)null);
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Favori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RefId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Favoriler", (string)null);
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Hadis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("Hadisler", (string)null);
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Sure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArapcaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AyetSayisi")
                        .HasColumnType("int");

                    b.Property<int>("CuzNo")
                        .HasColumnType("int");

                    b.Property<int>("InisSirasi")
                        .HasColumnType("int");

                    b.Property<int>("SayfaNo")
                        .HasColumnType("int");

                    b.Property<string>("SureAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SureNo")
                        .HasColumnType("int");

                    b.Property<string>("Yer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sureler", (string)null);
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnahtarKelimeler")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TemaAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Temalar", (string)null);
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Ayet", b =>
                {
                    b.HasOne("KuranGuide.Domain.Entities.Sure", "Sure")
                        .WithMany("Ayetler")
                        .HasForeignKey("SureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuranGuide.Domain.Entities.Tema", "Tema")
                        .WithMany("Ayetler")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sure");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Favori", b =>
                {
                    b.HasOne("KuranGuide.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("Favoriler")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Hadis", b =>
                {
                    b.HasOne("KuranGuide.Domain.Entities.Tema", "Tema")
                        .WithMany("Hadisler")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("Favoriler");
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Sure", b =>
                {
                    b.Navigation("Ayetler");
                });

            modelBuilder.Entity("KuranGuide.Domain.Entities.Tema", b =>
                {
                    b.Navigation("Ayetler");

                    b.Navigation("Hadisler");
                });
#pragma warning restore 612, 618
        }
    }
}
